### ISSUE TITLE
Kernel dropped into fastboot

### ISSUE THREAD

**Issue by azwhikaru** [snoopy112/hiby_r5_kernel_module#1]
When i compile a new kernel using source from https://github.com/android-linux-stable/msm-3.18.git and the defconfig extracted from Hiby R5, i replace it into stock boot.img, the device repeatedly enters fastboot

did I miss any steps?

**Comment by snoopy112** [comment]
I'm not sure if it's possible to replace the old kernel with new one on device, I haven't tried it by myself. Building kernel is necessary to compile modules on a PC.

**Comment by azwhikaru** [comment]
In other words, does it mean that you only built and installed the kernel module and did not use the new zImage you built?

**Comment by snoopy112** [comment]
Yes, I just copy module to /vendor/lib/modules and create /vendor/etc/init/hw/init.mydevice.rc file in vendor partition:
```
on property:sys.boot_completed=1
    insmod /vendor/lib/modules/vol_keys.ko
```

**Comment by azwhikaru** [comment]
thanks for your reply

i dont know what form the validation for boot and recovery in r5, but when i try to boot TWRP, it loops into 900E; when i use the built kernel, it loops into fastboot, but strangely: magisk works fine

**Comment by snoopy112** [comment]
I couldn't get TWRP for r5. I think it's due to locked bootloader?
Working stock repacked recovery I got only with Android Image Kitchen v3.8 but I quit that idea...

**Comment by azwhikaru** [comment]
this is weird, r5's aboot removes all fastboot commands like oem even reboot. but maybe borrow aboot from other msm8917 devices, i have done this kind of thing before, it worked fine on sdm660 and sdm845

through command getvar all found secure boot is off, so we can refresh the system, vendor even magisk patched boot. i rely on this , removed a lot of qualcomm debug tool that is useless in the system , but it may not be possible to replace the kernel until we turn off avb and unlock bootloader

**Comment by azwhikaru** [comment]
well, I flashed the wrong aboot on a recent refresh and the device seems to be bricked lol

but based on Qualcomm's boot sequence, i think a few days later, when the battery ran out and I reboot it, got into 9008 via sbl (now seemed to be stuck, cant shutdown, cant reboot, any key didn't work, the screen went off) (hopefully)

do you have similar experiences? i dont think damaging the aboot will cause the device to be completely bricked, maybe by shorting the USB port also can get into the 9008 as well, i havent tried that yet

**Comment by snoopy112** [comment]
No, I haven't :( Always get into 9008 by + and - while booting (it's a part of aboot?). If you can open back cover I think that would be a test points on MB.

**Comment by azwhikaru** [comment]
I thought the 9008 was part of the bootrom? because you can enter 9008 even without installing emmc. now I just dont know whether I can enter 9008 through key combination after the aboot is damaged:(

have you ever disassembled it? I havent disassembled it yet, and I cant find a clear TP on the pictures online

**Comment by azwhikaru** [comment]
aboot is stuck and now all key combinations dont work, which is annoying. .

**Comment by azwhikaru** [comment]
have you ever disassembled it? I havent disassembled it yet, and I cant find a clear TP on the pictures online

**Comment by snoopy112** [comment]
No, but I saw some pictures on head-fi hiby's [thread](https://www.head-fi.org/threads/r5-a-new-android-dap-by-hiby.912566/page-117#post-15493597) only. First of all let the battery drain and try to connect to PC with pressed + and - keys

**Comment by azwhikaru** [comment]
have never felt that the power consumption of r5 is so slow lol, making me wait for a few days..😢



---- Replied Message ----
| From | ***@***.***> |
| Date | 04/11/2024 21:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [snoopy112/hiby_r5_kernel_module] Kernel dropped into fastboot (Issue #1) |

No, but I saw some pictures on head-fi hiby's thread only. First of all let the battery drain and try to connect to PC with pressed + and - keys

**Comment by azwhikaru** [comment]
three days later, nothing happened, I dont even know if its on or off. just purchased a special cable called 'EDL Deep Flash Cable ' for shorting USB, hope this will work

**Comment by snoopy112** [comment]
Does it react to connection to PC? Long press on power button (~20 sec) also nothing reveal?

**Comment by azwhikaru** [comment]
Nothing happens, no matter what button I press and how long I keep pressing it, the screen backlight doesn't come on.

so i dont know if it is currently on or off

**Comment by azwhikaru** [comment]
I remember using qfil to flash an aboot from a lenovo tablet, and because of the firehose? when qfil tried to reboot it into edl mode, it disconnected until now

**Comment by snoopy112** [comment]
It's my first qcom device and I'm not faced with any problem with qfil...

**Comment by azwhikaru** [comment]
'EDL Deep Flash Cable' ready. it works on my snapdragon8 gen2 device, but r5 still unresponsive, maybe still a little battery left? its been almost five days, might have to give it two more days

**Comment by snoopy112** [comment]
Maybe put the device into refrigerator for several hours will help?

**Comment by azwhikaru** [comment]
A week has passed? still no progress, I think I will put it down for now. Maybe I will take it apart when I have time, or wait a few more days
